### ISSUE TITLE
Wish: (eyebrowse-restore "emacs@HOSTNAME") instead of interactively asking for configuration to restore

### ISSUE THREAD

**Issue by novoid** [FrostyX/eyebrowse-restore#1]
Hi,

I'd like to get a restore command where I may specify the configuration to restore in Elisp and not via asking me interactively.

For example, an optional parameter for `eyebrowse-restore` would do the trick:

```
(eyebrowse-restore "emacs@MYHOSTNAME")
;; OR:
(eyebrowse-restore (concat "emacs@" system-name))
```

# Background

My use-case seems to differ from the one mentioned in the README. I don't care about restoring the last state of an Emacs session. I only care about setting up the initial state of an Emacs session.

In my configuration from https://github.com/novoid/dot-emacs/blob/master/config.org, I'm "restoring" my eyebrowse session somewhat hacky:

```
       ;; setup my buffers the way I like it:
       (my-hsplit-last-buffer)          ;; split horizontal: left is agenda
       (my-mobile-org-import)           ;; switch to inbox.org (right side) and move latest input from mobileorg.org into inbox.org
       (eyebrowse-create-window-config) ;; create 2nd config for misc personal stuff
       (switch-to-buffer "notes.org")   ;; open notes buffer
       (eyebrowse-rename-window-config 2 "misc") ;; name 2nd config
       (eyebrowse-create-window-config) ;; create 3rd config for rise
       (switch-to-buffer "rise.org")    ;; open rise buffer
       (org-shifttab)                   ;; toggle visibility
[...]
```

While this somehow works, this is an ugly hack. Furthermore, some things aren't and I can't say why: additional splits and missing splits.

With `eyebrowse-restore`, there could be a much cleaner workflow for my use-case: restoring only the initial Emacs eyebrowse setup after the Emacs-boot and nothing else like periodically saving or saving on crash or similar.

For that, I just want to manually setup my initial buffers and eye-browse windows **once**, manually invoke `eyebrowse-restore-save-all` **once** and automatically restore this session at the end of my `init.el` at each Emacs start.

For that, I need to have a restore function that allows me to specify the configuration name so that I don't get asked interactively.

My current (initial) setup goes like that:

```
(use-package eyebrowse-restore
  :load-path  (lambda () (expand-file-name (concat my-user-emacs-directory "contrib/eyebrowse-restore/eyebrowse-restore.el")))
  :config
  (setq eyebrowse-restore-dir (expand-file-name (concat my-user-emacs-directory "etc/eyebrowse-restore-" system-name)))
  (make-directory eyebrowse-restore-dir "also create parents")
)
```

Note that I was not able to set up quelpa so I use only Melpa `use-package` and `use-package` with local `load-path` and manual `git pull`. That should not be an issue here.

**Comment by FrostyX** [comment]
Hello @novoid 

> My use-case seems to differ from the one mentioned in the README. I don't care about restoring the last state of an Emacs session. I only care about setting up the initial state of an Emacs session.

I totally understand, I was also trying to do this before.

> While this somehow works, this is an ugly hack.

Right? I think it would be a good idea for Eyebrowse to provide some way of configuring the initial workspaces. Maybe sometime :-)

But what you are asking for will be very easy to do in `eyebrowse-restore`. I will get to it today.

**Comment by novoid** [comment]
Alternatively or additionally: if there is only one single configuration file in the `eyebrowse-restore-dir`, don't ask, just apply because there is no other option than to apply this single file.

Some people might think that this is irritating the user because they ought to get asked. I'd prefer the "not being asked when there is only one option to choose from" approach.

**Comment by FrostyX** [comment]
I implemented both of the suggested features. Thank you for the feedback.
