### ISSUE TITLE
Please upload it to *elpa

### ISSUE THREAD

**Issue by novoid** [FrostyX/eyebrowse-restore#4]
Hi,

I do find this package very useful and use it every day.

Would you consider uploading it to MELPA/ELPA/...?

Thank you!

**Comment by FrostyX** [comment]
Thank you for the kind words @novoid.

> Would you consider uploading it to MELPA/ELPA/...?

Okay, it is decided. It shall be my first MELPA package :-)

**Comment by novoid** [comment]
Thank you very much. I know it's a hard thing to decide when you've never done the process - like myself as well.

**Comment by FrostyX** [comment]
>  I know it's a hard thing to decide when you've never done the process - like myself as well.

I wanted to add some of my packages to MELPA and learn how it works, but I didn't know which one, because I didn't know if anybody is even using them :D

Submitted a PR for MELPA, now we wait.

**Comment by FrostyX** [comment]
:partying_face: :partying_face: :partying_face: 
https://melpa.org/#/eyebrowse-restore
